name: Validate Module 1 Submissions

on:
  push:
    paths:
      - 'module-1/exercices/*.png'  # Vérifie les fichiers d'image des exercices

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if all exercise screenshots are uploaded
        run: |
          # Vérification de la présence des captures d'écran pour chaque exercice
          if [ ! -f "module-1/exercices/exercice1.png" ]; then
            echo "La capture d'écran de l'exercice 1 est manquante. Veuillez la soumettre."
            exit 1
          fi
          
          if [ ! -f "module-1/exercices/exercice2.png" ]; then
            echo "La capture d'écran de l'exercice 2 est manquante. Veuillez la soumettre."
            exit 1
          fi

          echo "Toutes les captures d'écran du module 1 sont présentes, validation réussie."

      - name: Move to next module
        if: success()
        run: |
          echo "Toutes les captures d'écran du module 1 ont été validées, vous pouvez passer au module suivant."
          
          # Tu peux également déclencher une action ici pour envoyer un message ou autoriser l'accès au module suivant
          # Exemple : Créer un fichier pour indiquer que le module est validé
          touch module-1/validated.txt
          echo "Module 1 validé et prêt pour la progression."

